#!/usr/bin/env bash

set -e

echo "Running pre-commit checks..."

cd packages/flutter_query

flutter analyze
flutter pub run import_sorter:main --exit-if-changed
dart format --output none --set-exit-if-changed .
flutter test test/src_new

echo "✓ All pre-commit checks passed!"
