name: query
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  equatable: ^2.0.5
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
