name: simple
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_query: ^0.2.0
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

dependency_overrides:
  flutter_query:
    path: ../../packages/flutter_query

flutter:
  uses-material-design: true
